import React, { useState } from 'react'; 
import { auth, db } from '../firebase';
 import { signInWithEmailAndPassword, createUserWithEmailAndPassword } from 'firebase/auth';
  import { useNavigate } from 'react-router-dom'; 
  import { doc, setDoc } from 'firebase/firestore';

export default 
function TherapistLogin() { const [isSignUp, setIsSignUp] = useState(false); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [name, setName] = useState(''); const navigate = useNavigate();

const handleAuth = async (e) => { e.preventDefault(); try { if (isSignUp) { const res = await createUserWithEmailAndPassword(auth, email, password); await setDoc(doc(db, "profiles", res.user.uid), { full_name: name, role: 'therapist', is_approved: true, // Therapists are usually auto-approved or admin-handled createdAt: new Date().toISOString() }); alert("Therapist Account Created!"); } else { await signInWithEmailAndPassword(auth, email, password); } // Use replace: true to prevent back-button issues navigate("/therapist-dashboard", { replace: true }); } catch (err) { alert(err.message); } };

return ( <div className="h-screen flex items-center justify-center bg-yellow-50 p-6"> <form onSubmit={handleAuth} className="bg-white p-8 rounded-3xl shadow-xl w-full max-w-md space-y-4"> <h2 className="text-2xl font-bold text-center text-yellow-600"> {isSignUp ? 'Therapist Registration' : 'Therapist Login'} </h2> {isSignUp && ( <input required placeholder="Full Name" className="w-full p-4 bg-gray-50 rounded-2xl border outline-none" onChange={e => setName(e.target.value)} /> )} <input required type="email" placeholder="Email" className="w-full p-4 bg-gray-50 rounded-2xl border outline-none" onChange={e => setEmail(e.target.value)} /> <input required type="password" placeholder="Password" className="w-full p-4 bg-gray-50 rounded-2xl border outline-none" onChange={e => setPassword(e.target.value)} /> <button type="submit" className="w-full p-4 bg-yellow-400 text-green-900 rounded-2xl font-bold"> {isSignUp ? 'Register' : 'Login'} </button> <p className="text-center text-sm text-yellow-600 font-bold cursor-pointer" onClick={() => setIsSignUp(!isSignUp)}> {isSignUp ? 'Back to Login' : 'New Therapist? Register Here'} </p> </form> </div> );}